---
- name: Create ansible/jupyterlab
  hosts: all

  vars:
    # TCS inputs
    image: "{{ lookup('ansible.builtin.env', 'ANSIBLE_VAR_jupyterhub_image', default='jupyterhub/jupyterhub') }}"
    registry: "{{ lookup('ansible.builtin.env', 'ANSIBLE_VAR_jupyterhub_registry', default='index.docker.io') }}"
    version: "{{ lookup('ansible.builtin.env', 'ANSIBLE_VAR_jupyterhub_version', default='3.1.1') }}"

    # osism.services.manager
    docker_user: ubuntu
    docker_opts:
      mtu: 1300

  roles:
    - role: osism.services.docker
