---
blueprint:
  author: Christian Berendt
  repository_server: https://github.com
  repository: thecloudsphere/hello-world
  name: python/hello-world
  versions:
    - version: main
  description: |
    Run a python script.

  environment:
    repository: thecloudsphere/registry
    name: python/base
    version: "3.10"

  inputs: []
  outputs: []
